apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: atto-platform-openclaw
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: flux-github-https
  url: https://github.com/attoistmo-lgtm/atto-platform-openclaw.git
