apiVersion: v1
kind: Secret
metadata:
    name: atto-platform-openclaw-secrets
    namespace: openclaw-system
type: Opaque
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:Pib+2jykhY0m61b0wmW9hvi3mdfWzYPr7j5+sMLVT+lfAyHhvecnRZmFe5j02D/J30LvVlZqCDMHmzyXp1InOpwZ7yC8S0UY,iv:MFzCSonWW2/WXUZFyQKOMr06rmd2A9NoBkk60slrAs8=,tag:JggT1Kwxzcy6pYAMzur//g==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:4Oa9lmNKp8dNrjjtuoLKo3UTY7hLoFM7UOQJ4S8wk48=,iv:lCXwmt1CxSDWi17RSX2dUF1bHMRaPLDNm/6AdcI9v3U=,tag:537knstaknWwWZWnfcXBDA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:oSJB89xXPziOvOm2AVY6jup/8V2jWtcSaR8D5ZM6,iv:mqYcqe2JbjcZa3XLhw05/a4CpyA1YkA0D9c2Vv0w768=,tag:7LEgjFVu11S88rszMuFqGg==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:iAkGlhIojgctxxPsv8MtDK5e2DxYg7pleBWJ2EcyOTzG2CpxJIfO,iv:i+xIBQBgerF+yZpkwYA9U8fCI7iy1YE7KPCkfosDBdA=,tag:t8EHMZB+hNjpJ+OaHG0r2g==,type:str]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:oMp3p2H01Lvc7ebhDxu7/nniyA0W/XjdMEx9lqeYaUruIlQ=,iv:viD4aIg5OOiYuDiRP2jsKpYa0prL/X599Wy5vifX3Pk=,tag:Gm2NQQKKaw+ORwzI2QUurw==,type:str]
    WHATSAPP_TOKEN: ENC[AES256_GCM,data:X/Gu2l/131CYyLQBqOAX7e++sy4xcpuP39XQo6fu0/7y5Q==,iv:aLVGKIqpVASgSYBPsCJDlWMczTtzKStuoyB1218KcXk=,tag:WnrywIG4gBaCgGmN02R5mQ==,type:str]
    OPENCLAW_MASTER_KEY: ENC[AES256_GCM,data:Czftt7xvU7+qQFxca81YMZggxz8cQTOGwUr70Z9Of6nIOphIplPB+Iqx4UEeSSpx1WU0o0a9THwhlMsvjqjOAOMpjbu6hPnT6A==,iv:KYeX2GxBgL8aS4gqtlrZtz8rWa1NBz50r6hJcUHjSKg=,tag:bns8uf3ChsTjFNZZ2nqTpw==,type:str]
sops:
    lastmodified: "2026-06-23T19:49:26Z"
    mac: ENC[AES256_GCM,data:frPmQnTV5Adzq48cG2775hH7NrwwnR2vKvqOzf9sFJdtVPWB9ut/obicjHvH6+h8Y5M/alSxQP5nZ+1Vp6+oJHtRe9eOmSnByapZKMTkj6KXtsbgkGUDPsWwELTxKczjGMdmiAtCAQKmw+lrvwuuWmVkVcZY7oO4qwC/6d5CqNA=,iv:nPeUhifgHP8vyxz0sZkCluTatCcTCXdtzsF15EuObYI=,tag:N1PJR0Hx2pG4UrF8Omzlmg==,type:str]
    pgp:
        - created_at: "2026-06-23T19:49:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5PF5JOgTKZxARAAukv21Q0J42YFRkEZqVDS8vcbGIxbdhgc2GEGVYpuOv59
            6BFhNCpPdIAni6ouGo0RCe8XhcxVtDdM4TfpLGMa2PHAqWPP2Gyx5gEl7fP3Mtly
            9YuzfqIkSkeW1xK69ZTyRBcIL1+7H6s+V7i14d/6QjHZPlxdChQdgnATaE/EDgjA
            6rBKkSIqLZDt3RsV/+0t/CsCnyjNuUuHrm/0gk3eUlV0FGvLsr2Ls4yn9AXz4lzR
            FSQhoaFbYm5Cc7EnGSxGOEhcHeLoG3y2NP8Ummf538x3hU+XfnI1uDFD4KFFEKNO
            x7QcfmLdxHNsOqp3bBqj+V/KURLBMdnFKqrXeKh0d9Y/klX3G9n8k3v//8qb2P+o
            wKr9yWGVZvUBWGgovRMrppJUKm+710ygqGBTa43fiYuDzbdzYkgMgrIHAJDIBxCN
            U28jQz6k99dwvQXbf8MQX/fFj622ZWy9tlWvDyGTXwceUfYuqaJCVcvTgr6I/v3d
            PFN7Bi6z3Np0FhDzDwbsqE4d4RxO+NiUwLzS2435EEatAsX28NR6T/IzicpWxT+T
            3jtpcLIpiYRSsWqZNiklzYfeNW+KG08moCRP2RyZa5GKyK7fFvg+PQQAwLeH//hP
            Ye23+gAve8rtDU9jDsB5xanf7NRKmtN9trGms60Yhd6D9N7nVjNw5ScTHgkS9XDS
            XAHiSG58jEwCer6CWGvJZGxIN8qwUSHGzGfvNhFSi6n1sAgT1tk0wpIGRGPvjEz3
            PtAtEIda/bDDCwRPfg1WlAEuzfbigXgDEYWESwZdDIHZKrnv23Ak+9UYK2Hi
            =61XJ
            -----END PGP MESSAGE-----
          fp: A5E668673C8EF04923F3C5D393C5E493A04CA671
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
